Course improvements
vtex-apps/store-framework-course pull request #10
Opened 2020-06-30 18:46 UTC by FabianaFerreira

- [ ] Fix missing translation on CSS handles step
- [ ] Put every hex color code in lower case to avoid problems when evaluating anwser
- [ ] Put in the pdp3 step a brief text that explains that we want `image` as prop value of `showValueVariation`
- [ ] Reference to Github markdown cheatsheet when talking about h3 and h4 headers
- [ ] Social network names should accept both lower and upper case on footer step
- [ ] Add reference to the next course on the last step of this course
- [ ] Make changes on both `menu` and `menu-flex` to avoid problems of declaring blocks on the wrong file

2020-07-03 14:57 UTC, saviomuniz requested changes

2020-07-03 14:57 UTC, saviomuniz commented on course/steps/responsive/pt.md
> +    > Se você não se lembra da sintaxe de Markdown, é possível consultá-la em [Github Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
Eu preferiria colocar um link mais técnico aqui, inclusive a gente já tem um no step do hello world, acho que só referenciá-lo. Apesar de ser uma documentação rápida e bacana, está num repo particular e não é nenhuma documentação oficial, além de ser direcionado para o md do Github

2020-07-10 19:54 UTC, lucis approved these changes

2020-07-10 19:59 UTC, gris approved these changes
![image](https://user-images.githubusercontent.com/11340665/87193240-ab3a5600-c2ce-11ea-8433-3aa3260b6858.png)

2020-07-10 20:16 UTC, merged